name: al_furqan_school
description: A new Flutter project.
publish_to: 'none'
version: 3.0.5+105
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinch_zoom: ^1.0.0

  get: ^4.6.1
  map_launcher: ^2.2.2
  new_version: ^0.3.0
  provider: ^6.0.2
  share_plus: ^6.3.4
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  carousel_slider: ^4.0.0
  webview_flutter: ^4.2.2
  dio: ^5.2.0
  firebase_messaging: ^14.6.2
  easy_pdf_viewer: ^1.0.6
  expandable: ^5.0.1
  file_picker: ^5.2.10
  path_provider: ^2.0.10
  path: ^1.8.0
  permission_handler: ^10.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^14.1.1
  flutter_app_icon_badge: ^2.0.0
  url_launcher: ^6.0.20
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.4.1
  connectivity: ^3.0.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
dependency_overrides:
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - i18n/ar.json
    - i18n/en.json
  fonts:
    - family: DroidKufi
      fonts:
        - asset: assets/fonts/DroidKufiRegular.ttf
        - asset: assets/fonts/DroidKufiBold.ttf
          weight: 700