name: al_furqan_school
description: A new Flutter project.
publish_to: 'none'
version: 3.2.1+110
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  map_launcher: ^4.4.3
  provider: 6.1.5+1
  share_plus: 12.0.1
  cached_network_image: ^3.4.1
  shared_preferences: 2.5.4
  in_app_update: 4.2.5
  carousel_slider: 5.1.2
  webview_flutter: 4.13.1
  dio: 5.9.1
  firebase_messaging: 16.1.1
  expandable: ^5.0.1
  flutter_html: ^3.0.0
  flutter_local_notifications: 20.1.0
  firebase_analytics: 12.1.2

  url_launcher: 6.3.2
  firebase_core: 4.4.0
  file_picker: 10.3.10
  image_picker: 1.2.1
  open_file: 3.5.11
  file_saver: 0.3.1

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - i18n/ar.json
    - i18n/en.json
  fonts:
    - family: DroidKufi
      fonts:
        - asset: assets/fonts/DroidKufiRegular.ttf
        - asset: assets/fonts/DroidKufiBold.ttf
          weight: 700