name: al_furqan_school
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_downloader: ^0.31.0
  get: ^4.6.1
  map_launcher: ^2.2.2
  provider: ^6.0.2
  share_plus: ^4.0.4
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  carousel_slider: ^4.0.0
  webview_flutter: ^2.1.0
  dio: ^4.0.4
  firebase_messaging: ^11.2.6
  expandable: ^5.0.1
  flutter_html: ^2.1.0
  flutter_local_notifications: ^9.3.2
  url_launcher: ^6.0.20
  flutter_launcher_icons: "^0.9.2"
  firebase_core: ^1.17.0
  connectivity: ^3.0.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - i18n/ar.json
    - i18n/en.json
  fonts:
    - family: DroidKufi
      fonts:
        - asset: assets/fonts/DroidKufiRegular.ttf
        - asset: assets/fonts/DroidKufiBold.ttf
          weight: 700