// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class I18nRes {
  I18nRes._();

  static const String PROJECT_NAME = 'al_furqan_school';
  static const String PROJECT_VERSION = '3.2.1+110';
  static const String AR = 'i18n/ar.json';
  static const String EN = 'i18n/en.json';
}
