// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9DU-7S7yMm6oqSwjIivefYFcC8g-UR7g',
    appId: '1:942256929814:android:5d76e63fd87420adc28937',
    messagingSenderId: '942256929814',
    projectId: 'alfarquan-c4250',
    databaseURL: 'https://alfarquan-c4250-default-rtdb.firebaseio.com',
    storageBucket: 'alfarquan-c4250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5AG8oHwm-kxdJ5AlqvJz2qNo6T7mOZdU',
    appId: '1:942256929814:ios:8c766a02f6eed661c28937',
    messagingSenderId: '942256929814',
    projectId: 'alfarquan-c4250',
    databaseURL: 'https://alfarquan-c4250-default-rtdb.firebaseio.com',
    storageBucket: 'alfarquan-c4250.appspot.com',
    iosClientId: '942256929814-5gefoltsvikcefb54j4rkkike59oc8fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.alFurqanSchool',
  );
}
